name: Stage

on:
  push:
    branches:
      - stage

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'stage'
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '12'
        check-latest: true
    - run: npm install --production
    - run: npm run stage
    - run: |
        sed --in-place 's/"name": "\(.*\)"/"name": "\1 - QA version"/' build/manifest.json
    - run: zip -r language-settings-manager.stage.zip build/*
    - uses: Passiverecords/chrome-extension-upload-action@1.4.1
      name: Release
      id: release
      with:
        refresh-token: '${{ secrets.CHROME_WEBSTORE_REFRESH_TOKEN }}'
        client-id: '${{ secrets.CHROME_WEBSTORE_CLIENT_ID }}'
        client-secret: '${{ secrets.CHROME_WEBSTORE_CLIENT_SECRET }}'
        file-name: './language-settings-manager.stage.zip'
        app-id: 'kbigminlcdmikfhdkfjcmocnjhkikhpp'
        publish: false
